apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb
  template:
    metadata:      
      labels:
        app: sb
    spec:
      containers:
      - name: ip-container
        image: 10.7.7.4:5000/sbimage:24
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sb
spec:
  selector:
    app: sb
  ports:
    - name: svc-port
      protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 31000
  type: NodePort
