apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:      
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: oolralra/hnginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
spec:
  selector:
    app: httpd
  ports:
    - name: svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  type: NodePort
